// <auto-generated />
using System;
using ERP.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ERP.Infra.Data.Migrations
{
    [DbContext(typeof(EventStoreSQLContext))]
    partial class EventStoreSQLContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ERP.Domain.Core.Events.StoredEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<Guid>("AggregateId")
                        .HasColumnName("aggregate_id");

                    b.Property<string>("Data")
                        .HasColumnName("data");

                    b.Property<string>("MessageType")
                        .HasColumnName("acao")
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnName("data_cadastro");

                    b.Property<string>("User")
                        .HasColumnName("usuario")
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("pk_stored_event_id");

                    b.ToTable("stored_events");
                });
#pragma warning restore 612, 618
        }
    }
}
