DROP DATABASE ERP;
CREATE DATABASE ERP;

USE ERP;

DELETE FROM ASPNETROLECLAIMS;
DELETE FROM ASPNETROLES;
DELETE FROM ASPNETUSERCLAIMS;
DELETE FROM ASPNETUSERLOGINS;
DELETE FROM ASPNETUSERROLES;
DELETE FROM ASPNETUSERS;
DELETE FROM ASPNETUSERTOKENS;
DELETE FROM CNAES;
DELETE FROM EMPRESAS;
DELETE FROM ESTABELECIMENTOS;
DELETE FROM GRUPOS_EMPRESARIAIS;
DELETE FROM STORED_EVENTS;
DELETE FROM USUARIOS;


SELECT *
FROM GRUPOS_EMPRESARIAIS